spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  error:
    include-message: always

app:
  imagesPath: images
  imagesEndpoint: /images